### ISSUE TITLE
Add letter styles to CSS

### ISSUE THREAD

**Issue by ericawarren** [macmillanpublishers/bookmaker_assets#16]
Per request for Tor.com, by late May for final pass.

Letter Ext Address (ladd)
Letter Ext Closing (lcl)
Letter Ext Dateline (ldl)
Letter Ext General (extl)
Letter Ext Headnote (hn)
Letter Ext Postscript (lps)
Letter Ext Salutation (lsa)
Letter Ext Signature (lsig)
Letter Ext Body Text (ltx)
Letter Ext Body Text No-Indent (ltx1)

**Comment by nelliemckesson** [comment]
Wrote to Jamie Stafford-Hill, re: creating designs for these styles.
