### ISSUE TITLE
First line of "Extract - Verse" block is indented in PDF.

### ISSUE THREAD

**Issue by ericawarren** [macmillanpublishers/bookmaker_assets#25]
Example files [here](https://www.dropbox.com/sh/1g98wxhko0rbxtm/AADJjDzJagsxGMq1LEQeoUfka?dl=0), note PDF p. 155.

It looks like this:
```
blockquote p:first-child {
  text-indent: 0; }
```

overrides this:
```
*[class*="Extract-VerseorPoetryextv"] {
  font-style: italic;
  text-indent: -12pt;
  margin-left: 16pt;
  text-align: left; }
```

for the first paragraph, but since the latter has a *negative* `text-indent` value, the first line is 12 points further indented the other lines in the block.

I added this to a oneoff.css to fix this specific project:
```
[class*="Extract-VerseorPoetryextv"]:first-child {
font-style: italic;
text-indent: -12pt;
margin-left: 16pt;
text-align: left; }
```

**Comment by ericawarren** [comment]
Lauren also said that she's seen it in other extract styles as well, not just verse/poetry.

**Comment by nelliemckesson** [comment]
alright @mattretzer Matt this one is all yours. If you can get to it sometime during week of 9/19, that would be great.

**Comment by mattretzer** [comment]
That should be fine!  Thx!

**Comment by ericawarren** [comment]
If you need additional samples, I can ask Lauren if she can think of any off hand.

**Comment by ericawarren** [comment]
Also Lauren says that she needs this for a project due 10/10, if possible (we can always do oneoff.css if not, though).

**Comment by mattretzer** [comment]
pulled in, deployed & retested, all set for ebook & pdf css.
