### ISSUE TITLE
Add 4 new styles to pdf.css

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker_assets#50]
Add support for these 4 new styles to the core_tor.css, torDOTcom/pdf.css, and tor.com/novel.css. 

Please add each style as it's own scss file here: https://github.com/macmillanpublishers/bookmaker_assets/tree/master/pdfmaker/css/_modules, matching the way those files are named and set up. All formatting relevant to the style should be included in each scss file.

For the design, do the following:
Extract - Song Lyric (extsl): match "Extract-VerseorPoetryextv" formatting (and make sure to include the em definition as well) (https://github.com/macmillanpublishers/bookmaker_assets/blob/master/pdfmaker/css/core_tor.css#L1128)
Extract - Inscription (ins): copy Extract paragraph formatting (https://github.com/macmillanpublishers/bookmaker_assets/blob/master/pdfmaker/css/core_tor.css#L886) plus add italic and center.
Note Level-1 Subhead (n1): match Head Level 1 (https://github.com/macmillanpublishers/bookmaker_assets/blob/master/pdfmaker/css/core_tor.css#L811)
Note Level-2 Subhead (n2): match Head Level 2 (https://github.com/macmillanpublishers/bookmaker_assets/blob/master/pdfmaker/css/core_tor.css#L822)

**Comment by mattretzer** [comment]
These styles have been added & deployed as per: 
https://github.com/macmillanpublishers/bookmaker_assets/pull/51
