### ISSUE TITLE
[js] Suppress header block for PDFs - pdfmaker/css

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker_assets#52]
We will be adding a header block for every section and div.part element. We need to set this to display: none for all PDF CSS. (See https://github.com/macmillanpublishers/htmlmaker_js/issues/18).

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

submitted PR: https://github.com/macmillanpublishers/bookmaker_assets/pull/58

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

approved & merged!
