### ISSUE TITLE
Removing ctnp from manuscript for htmlmaker_js changes top margin

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/bookmaker_assets#61]
Because ChapTitleNonPrinting has a [top margin in the pdf css](https://github.com/macmillanpublishers/bookmaker_assets/blob/master/pdfmaker/css/core_tor.css#L759-L760), when I removed the ctnp from [this manuscript](https://www.dropbox.com/s/yiktrz90j4xb93q/9780765389831_MNU.docx?dl=0) for section-start-styling, I lose that top margin in the pdf (no change in the epub).  Expected output; just noting a discrepancy.

**Comment by mattretzer** [comment]
Same thing happened in [this document](https://www.dropbox.com/s/ua7t4hsjsryub5h/9780765395733_MNU_ctnp-epigraph-removed.docx?dl=0) when I removed the FMHeadNonPrinting from the Epigraph, I lost the top margin for the epigraph in the pdf.

**Comment by mattretzer** [comment]
We should handle this by adding a ctnp or fmnp or bmnp for any sections without a heading.

We should double-check that this is not already handled in htmlmaker_js.
And we should make sure that we are getting entries in theTOC / ncx for sections where we want them.  
This should happen in htmlmaker_postprocessing.rb

**Comment by mattretzer** [comment]
As I review this issue, just noting: h1's with class="Nonprinting" are getting inserted, just not ctnp's etc.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Submitted PR for review: https://github.com/macmillanpublishers/bookmaker/pull/186

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

merged into sectionstartstaging branch
