### ISSUE TITLE
[1] Check to make sure all section data-types have handling in css

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/bookmaker_assets#64]

**Comment by MacmillanWorkflows** [comment]
➤ 9491251705208 commented:

I checked those that need handling for pdf-css and added them to this issue: https://github.com/macmillanpublishers/bookmaker_assets/issues/67
We should check and see if these need any handling for epub-css too; for most of the ones that have popped up during testing, the epub output hasn't varied (except for heading links to TOC, not a CSS fix)

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

1 hr

**Comment by MacmillanWorkflows** [comment]
➤ erica.warren commented:

[Matthew Retzer](https://app.asana.com/0/9492427432407/9492427432407) I started this, taking more than 1 hours because even if the data-type isn't explicitly in the CSS, it can still be formatted correctly based on other rules, so I'm trying to test a variety of things. If I'm going about this wrong, please let me know.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

If correct styling is already applied, we don't need to worry about it.. I think in the case of 'Foreword' it just wasn't getting formatting from anywhere else.
I listed the other ones based on a very cursory search, so they may already be covered through other rules? That section-start-rules.json includes the class etc that every section start should have if you're not sure if an attribute will always be present:
https://github.com/macmillanpublishers/htmlmaker_js/blob/master/style_config.json#L199-L310

**Comment by MacmillanWorkflows** [comment]
➤ erica.warren commented:

[Matthew Retzer](https://app.asana.com/0/9492427432407/9492427432407) please review PR for this (same PR as for [[2] Section-Back-Ad became section data-type 'Appendix' in html, and generated leading blank page in pdf](https://app.asana.com/0/255449887586230/350345190346975))

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

approved!
