### ISSUE TITLE
[3] no pdf-css rules for data-type="foreword" (htmlmaker_js)

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/bookmaker_assets#67]
(Encountered when testing with our [test manuscript](https://www.dropbox.com/s/gwu0qxj1do11coy/bookmaker%20SECTION%20test%20MS%27.doc.docx?dl=0))

The Heading is not properly formatted (left justified) and there are no headers/footers

**Comment by mattretzer** [comment]
We can put these in as separate issues, but checking the core pdf css against section 'types' in htmlmaker_js' style_config.json, here are the 4 other section data-types that still need some handling in the pdf css:
        {"type": "introduction"}
        {"type": "afterword"}
        {"type": "glossary"}
        {"type": "index"}

**Comment by MacmillanWorkflows** [comment]
➤ 9491251705208 commented:

Introduction handling, same as preface, the other 3, same as Appendix

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

2.5 hrs
