### ISSUE TITLE
[8] Full page images are cropping / aligning strangely

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/bookmaker_assets#78]
From user:

> Bookmaker does something strange when ingesting two L and R images for a full page spread.
> 
> I supplied images that were 5.125" x 8.25" and included 11.5pts of ink-free gutter on the inside edge.
> 
> Image output in the pdf were modified by bookmaker.  As far as I can reconstruct, this is what it does:
> 1) whitespace is ignored / cropped off
> 2) an additional 11.5pts is also cropped from the inside edge
> 3) 11.5pts of whitespace is added back
> 4) the resulting image is then stretched horizontally back to 5.125"

> 3 and 4 may happen in reverse order, but what is definitely happening:
> • it's cropping from the inside edge incorrectly —it does this whether that space is blank or has art
> • it's stretching horizontally
>

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Walked through pitstop actions 1 by 1; images come in fine via CSS etc but there is a double-cropping of a sort happening. Edited images to account for this, sent Jamie this workaround. Felipe is checking with the vendor to see if on of the pitstop actions is still necessary is still necessary.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

moving to review until I hear back from user (Jamie Stafford-Hill)

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Have not heard from Jamie in 2 weeks, moving to Done.
